[default]
enabled_warnings = [
    "NoImplicitNet",
    "NoUnusedSignal",
    "NoUnusedParameter",
    "NoUnreachableCode",
    "NoVectorizedEnum",
    "RequireReset",
    "RequireLabel",
    "RequireOneModulePerFile"
]

disabled_warnings = [
    "NoBeginLabel",
    "NoBlankLine",
    "NoCaseDefault",
    "NoCommaAtEOL",
    "NoEmptyBegin",
    "NoEmptyModule",
    "NoEmptyPackage",
    "NoInitialBlock",
    "NoNestedIf",
    "NoParameterRedef",
    "NoResetAsync",
    "NoSelectWithX",
    "NoShortIf",
    "NoSyncAsyncResetMix",
    "NoTab",
    "NoTrailingSpace",
    "NoUnderscore",
    "NoUnnamedGenerate"
]

error_on_warning = false
